var obj = {
  "userId": 3814633,
  "appFlag": 1,
  "productId": "com.btang.thermometer.prime2.free_trial_yearly",
  "status": 1,
  "memberStatus": 1,
  "storeType": 1,
  "expiredTimestamp": 4102415999,
  "memberExpiredTimestamp": 4102415999,
  "bonusDays": 0,
  "memberBonusDays": 0,
  "subscriptionStartTimestamp": 1682899200,
  "goldPrimeFlag": 1,
  "group": 0,
  "flag": "NEW_SUBSCRIPTION_FREE_TRIAL",
  "source": "RegisterPage",
  "activityId": 383,
  "fromMissOut": false,
  "lastPurchaseTimestamp": 1682899200,
  "target": 0,
  "channel": "Unknown",
  "triggerType": 0,
  "unionStatus": 0,
  "unionAppFlag": 0,
  "unionTimestamp": 0,
  "giveMemberExpireTimestamp": 0,
  "subscriptionSource": 0,
  "period": 3,
  "primeSavedAmount": 0,
  "sandbox": false,
  "fromAds": false,
  "advertisementType": 0
};

$done({body: JSON.stringify(obj)});