var obj = JSON.parse($response.body);

obj.digital_subscriptions = [{
    "billing_type": "apple_monthly",
    "billing_frequency": "monthly",
    "cost_in_cents": 0,
    "country_code": "US",
    "currency_code": "USD",
    "expires_at": 4102415999,
    "id": "80b6930d764a45eab8be09e484750922",
    "is_active": true,
    "name": "Peloton App Membership",
    "original_purchase_date": 1682646685,
    "owner": {
      "block_explicit": false,
      "block_prenatal": false,
      "disable_explicit_warning": false,
      "created_at": 1682646619,
      "id": "833c3ab8a31d4d89baad540d975bda30",
      "image_url": "https://res.cloudinary.com/peloton-cycle/image/upload/f_jpg/default_user_images/backgrounds/16",
      "is_effort_score_enabled": true,
      "is_profile_private": false,
      "is_provisional": false,
      "last_workout_at": null,
      "location": "",
      "total_followers": 0,
      "total_following": 0,
      "total_non_pedaling_metric_workouts": 0,
      "total_pedaling_metric_workouts": 0,
      "total_workouts": 0,
      "username": "engrbee",
      "workout_counts": []
    },
    "platform": "apple",
    "shared_user_set": [],
    "status": "active_normal",
    "status_text": "Active",
    "stream_limit": 3,
    "total_active_streams": 0,
    "tier_id": null,
    "tier_type": null,
    "user_id": "833c3ab8a31d4d89baad540d975bda30",
    "is_trial": false,
    "user": {
      "block_explicit": false,
      "block_prenatal": false,
      "disable_explicit_warning": false,
      "created_at": 1682646619,
      "id": "833c3ab8a31d4d89baad540d975bda30",
      "image_url": "https://res.cloudinary.com/peloton-cycle/image/upload/f_jpg/default_user_images/backgrounds/16",
      "is_effort_score_enabled": true,
      "is_profile_private": false,
      "is_provisional": false,
      "last_workout_at": null,
      "location": "",
      "total_followers": 0,
      "total_following": 0,
      "total_non_pedaling_metric_workouts": 0,
      "total_pedaling_metric_workouts": 0,
      "total_workouts": 0,
      "username": "engrbee",
      "workout_counts": []
    }
  }];

$done({body: JSON.stringify(obj)});