var obj = {
  "name": "engrbee Services",
  "handle": "engrbee",
  "bio": null,
  "twitter_handle": null,
  "github_handle": null,
  "location": null,
  "initials": "ENB",
  "avatar_placeholder_color": "#D47600",
  "slack_community_username": null,
  "slack_community_user_id": null,
  "created_at": 1684985066,
  "website_anchor": null,
  "website": null,
  "username": "engrbee",
  "avatar": null,
  "client_flags": {},
  "eligible_for_pro_features": true,
  "eligible_for_ai": true,
  "eligible_for_gpt4": true,
  "eligible_for_cloud_sync": true,
  "stripe_subscription_status": null,
  "stripe_subscription_interval": null,
  "has_payments": true,
  "stripe_subscription_canceled_at": null,
  "stripe_subscription_current_period_end": null,
  "has_active_subscription": true,
  "email": "engrbee@gmail.com",
  "any_organization_has_running_subscription": false,
  "can_upgrade_to_pro": false,
  "admin": false,
  "publishing_bot": false,
  "any_organization_has_active_subscription": false,
  "organizations": [],
  "swag_info": null
};

$done({body: JSON.stringify(obj)});
